title:        <a href = "/">R&sup2</a>
tagline:      A personal Blog
description:  R, Finance and statistics
url:          http://royr2.github.com
author:
  name:       ''
  email:      ''
markdown:     kramdown
highlighter:  pygments
gems:         [jekyll-paginate]
paginate:     4
analytics :
  provider : google
  google :
      tracking_id : 'UA-57026003-1'
