title:        R-Squared
tagline:      ''
description:  'R, Finance, Statistics'
url:          http://royr2.github.io
version:      ''
author:
  name:       ''
  email:      ''
markdown:     kramdown
permalink:    ''
highlighter:  rouge
paginate:     5
