title:        <a href = "/">R&sup2</a>
tagline:      ''
description:  A personal blog about my fumblings with statistics, finance and anything  R
url:          http://royr2.github.com
author:
  name:       ''
  email:      'riddhiman.roy@gmail.com'
markdown:     kramdown
highlighter:  pygments
gems:         [jekyll-paginate]
paginate:     5
analytics :
  provider : google
  google :
      tracking_id : 'UA-57026003-1'
